name: backend-dev-ci-cd
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Make zip file
        run: zip -qq -r ./da-ily.zip .
        # AWS S3에 빌드파일 배포
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./da-ily.zip s3://da-ily-bucket
      - name: Code deploy
        run: aws deploy create-deployment --application-name Da-ily --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name Daily-Api-Server --s3-location bucket=da-ily-bucket,bundleType=zip,key=da-ily.zip
